### ISSUE TITLE
could you add a readme?

### ISSUE THREAD

**Issue by tttp** [VishalAgarwal/CiviWebExtension#1]
copy paste of your latest blog for instance would be great

thanks for your participation in GSoC, happy to see the result

X+

**Comment by knockiiing** [comment]
Hey buddy,

I wanted to have a go of this extension on staging environment. Can you send me the link to the extension?

Thx

**Comment by VishalAgarwal** [comment]
Hey,

Here is the link to the github repository:
https://github.com/VishalAgarwal/org.civicrm.webtracking

Sorry for the late response.

On Wed, Sep 2, 2015 at 12:50 PM, knockiiing notifications@github.com
wrote:

> Hey buddy,
> 
> I wanted to have a go of this extension on staging environment. Can you
> send me the link to the extension?
> 
> Thx
> 
> Sent from my iPhone
> 
> > On 02 Sep 2015, at 08:34, xavier dutoit notifications@github.com
> > wrote:
> > 
> > copy paste of your latest blog for instance would be great
> > 
> > thanks for your participation in GSoC, happy to see the result
> > 
> > X+
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/VishalAgarwal/org.civicrm.webtracking/issues/1#issuecomment-136959938
> .

## 

Thank You,
Vishal Agarwal

**Comment by VishalAgarwal** [comment]
Hey,

Yeah I will do it over the weekend. I will add a few instructions about how
to get started with the repository

Glad that you liked my project

On Wed, Sep 2, 2015 at 12:04 PM, xavier dutoit notifications@github.com
wrote:

> copy paste of your latest blog for instance would be great
> 
> thanks for your participation in GSoC, happy to see the result
> 
> X+
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/VishalAgarwal/org.civicrm.webtracking/issues/1.

## 

Thank You,
Vishal Agarwal
